# Generated by Django 2.2.7 on 2019-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ad ve soyad')),
                ('subject', models.CharField(max_length=50, verbose_name='Konu')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='telefon')),
                ('content', models.TextField(verbose_name='mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('readed', 'Okundu'), ('deleted', 'Silindi')], default='new', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
