# Generated by Django 2.2.7 on 2019-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ad')),
                ('surname', models.CharField(max_length=50, verbose_name='soyad')),
                ('position', models.CharField(max_length=50, verbose_name='pozisyon')),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='fotoğraf')),
                ('profile', models.TextField(verbose_name='özgeçmiş')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='telefon')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='linkedin')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
