# Generated by Django 2.2.7 on 2019-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0002_auto_20191211_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
