# Generated by Django 2.2.7 on 2019-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0003_attorney_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
    ]
