# Generated by Django 2.2.7 on 2020-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0006_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='phone',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
    ]
