# Generated by Django 2.2.7 on 2020-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0007_auto_20200116_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='200*75 px'),
        ),
    ]
