# Generated by Django 2.2.7 on 2020-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0008_firm_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
