# Generated by Django 2.2.7 on 2020-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0009_attorney_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorney',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='attorney',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='fotoğraf 600*700px'),
        ),
    ]
