# Generated by Django 2.2.7 on 2020-05-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0011_auto_20200507_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='twitter',
        ),
    ]
