# Generated by Django 2.2.7 on 2020-05-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0012_auto_20200514_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firm',
            old_name='working_hour',
            new_name='working_hours',
        ),
    ]
