# Generated by Django 2.2.7 on 2020-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0013_auto_20200514_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
