# Generated by Django 2.2.7 on 2020-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0014_auto_20200515_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='telefon'),
        ),
    ]
