# Generated by Django 2.2.7 on 2020-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='1920*700 px boyutunda resim yükleyiniz', null=True, upload_to='carousel'),
        ),
    ]
