# Generated by Django 2.2.7 on 2019-12-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
