# Generated by Django 2.2.7 on 2020-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0004_auto_20191211_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Soru')),
                ('answer', models.CharField(max_length=550, verbose_name='Cevap')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
