# Generated by Django 2.2.7 on 2020-01-30 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicearea',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
