# Generated by Django 2.2.7 on 2020-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0006_auto_20200130_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
