# Generated by Django 2.2.7 on 2020-05-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0007_practicearea_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPracticeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='practicearea',
            options={'ordering': ['-number']},
        ),
    ]
