# Generated by Django 2.2.7 on 2020-05-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0008_auto_20200514_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_area.CategoryPracticeArea'),
        ),
    ]
